"""Layer 0 schema — the seven tables of 04-layer-0.md §2.

Written by hand rather than autogenerated, so that the enumerated types, the
no-hard-delete triggers, and the extension are created and dropped explicitly and
the migration is genuinely reversible in both directions.

Revision ID: 0001_layer_0_schema
Revises:
Create Date: 2026-08-13
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_layer_0_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Every enumerated type §2 names, with exactly the values it lists.
ENUM_TYPES: dict[str, tuple[str, ...]] = {
    "message_role": ("user", "val", "system"),
    "model_call_task_type": (
        "conversation",
        "classification",
        "strip",
        "blind_position",
        "title",
    ),
    "model_call_status": ("ok", "error", "refused"),
    "execution_event_type": ("accepted", "rejected", "revision_requested", "corrected"),
    "reason_source": ("stated", "inferred", "absent"),
    "deliberation_confidence": ("high", "medium", "low"),
    "deliberation_ordering": ("enforced", "contaminated"),
    "deliberation_outcome": ("updated", "held", "overridden", "agreed_from_start"),
    "deliberation_classification": ("consequential", "uncertain"),
    "deliberation_classified_by": ("automatic", "user", "val"),
}

TABLES: tuple[str, ...] = (
    "projects",
    "conversations",
    "messages",
    "personas",
    "model_calls",
    "execution_events",
    "deliberations",
)

# §2.3 — no table permits hard delete at Layer 0. Corrections preserve lineage
# (00-charter.md invariant 14), and audit is append-only (invariant 31). This is
# enforced by the database rather than by convention, because a convention is not
# a control.
FORBID_HARD_DELETE_FUNCTION = """
CREATE FUNCTION val_forbid_hard_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION
        'hard delete is not permitted on % at Layer 0 (04-layer-0.md §2.3)',
        TG_TABLE_NAME
        USING ERRCODE = 'restrict_violation';
END;
$$;
"""


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type rather than creating it inline."""
    return postgresql.ENUM(*ENUM_TYPES[name], name=name, create_type=False)


def _uuid_pk() -> sa.Column[sa.Uuid[object]]:
    """Time-ordered UUID primary key (PostgreSQL 18 `uuidv7()`)."""
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("uuidv7()"),
    )


def _timestamp(name: str, *, default_now: bool = True) -> sa.Column[sa.TIMESTAMP]:
    """Timezone-aware timestamp column."""
    return sa.Column(
        name,
        postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.text("now()") if default_now else None,
    )


def upgrade() -> None:
    """Create the Layer 0 schema."""
    # pgvector is required to be present from WP-0.2 even though §2 names no
    # vector column. Retrieval arrives at WP-0.7; the extension is installed now
    # so that the store is what the work package says it is.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    for name, values in ENUM_TYPES.items():
        rendered = ", ".join(f"'{value}'" for value in values)
        op.execute(f"CREATE TYPE {name} AS ENUM ({rendered})")

    # --- §2.1 Core -----------------------------------------------------------

    op.create_table(
        "projects",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        # §2 names `status` but does not enumerate its values. Left as text
        # rather than given an invented vocabulary.
        sa.Column("status", sa.Text(), nullable=False),
        _timestamp("created_at"),
        _timestamp("updated_at"),
        sa.PrimaryKeyConstraint("id", name="pk_projects"),
        sa.UniqueConstraint("slug", name="uq_projects_slug"),
    )

    op.create_table(
        "conversations",
        _uuid_pk(),
        # Nullable: "no project" is a real, explicit state, not a null accident.
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        _timestamp("started_at"),
        _timestamp("last_message_at"),
        sa.PrimaryKeyConstraint("id", name="pk_conversations"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_conversations_project_id",
            ondelete="NO ACTION",
        ),
    )

    op.create_table(
        "messages",
        _uuid_pk(),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", _enum("message_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        _timestamp("created_at"),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        # §2.3 — every message resolves to a conversation.
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_messages_conversation_id",
            ondelete="NO ACTION",
        ),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_messages_conversation_id_sequence"
        ),
        sa.CheckConstraint("sequence > 0", name="sequence_positive"),
    )

    op.create_table(
        "personas",
        _uuid_pk(),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        _timestamp("activated_at", default_now=False),
        sa.Column("authored_by", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_personas"),
        sa.UniqueConstraint("version", name="uq_personas_version"),
    )
    # WP-0.5 loads "the active personas row", singular.
    op.create_index(
        "uq_personas_single_active",
        "personas",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )

    # --- §2.2 Capture --------------------------------------------------------

    op.create_table(
        "model_calls",
        _uuid_pk(),
        _timestamp("created_at"),
        # The configuration, not a bare model string. §2 names no configuration
        # table, so this carries no foreign key at Layer 0. The Model
        # Configuration Registry arrives at WP-0.4.
        sa.Column("model_config_id", postgresql.UUID(as_uuid=True), nullable=False),
        # Denormalised deliberately — a retired config must still resolve
        # historically.
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model_identifier", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.BigInteger(), nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), nullable=False),
        # Computed at call time from the config's rates. Never recomputed later.
        sa.Column("cost", sa.Numeric(14, 6), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("task_type", _enum("model_call_task_type"), nullable=False),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("provider_request_id", sa.Text(), nullable=False),
        sa.Column("status", _enum("model_call_status"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_model_calls"),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_model_calls_project_id", ondelete="NO ACTION"
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_model_calls_conversation_id",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="fk_model_calls_message_id",
            ondelete="NO ACTION",
        ),
        sa.CheckConstraint("tokens_in >= 0", name="tokens_in_non_negative"),
        sa.CheckConstraint("tokens_out >= 0", name="tokens_out_non_negative"),
        sa.CheckConstraint("cost >= 0", name="cost_non_negative"),
        sa.CheckConstraint("latency_ms >= 0", name="latency_ms_non_negative"),
    )

    op.create_table(
        "execution_events",
        _uuid_pk(),
        _timestamp("created_at"),
        # Nullable to match conversations.project_id. See schema.py for why.
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", _enum("execution_event_type"), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        # Nullable, but a null reason is a defect to be surfaced, not a normal
        # state.
        sa.Column("reason", sa.Text(), nullable=True),
        # No default. Stated and inferred are different evidence.
        sa.Column("reason_source", _enum("reason_source"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_execution_events"),
        # §2.3 — cascades on nothing. It outlives the conversation.
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_execution_events_project_id",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_execution_events_conversation_id",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="fk_execution_events_message_id",
            ondelete="NO ACTION",
        ),
        sa.CheckConstraint(
            "(reason IS NULL) = (reason_source = 'absent')",
            name="reason_matches_source",
        ),
    )

    op.create_table(
        "deliberations",
        _uuid_pk(),
        _timestamp("created_at"),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("confidence", _enum("deliberation_confidence"), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("stripped_content", sa.Text(), nullable=False),
        # No default. Whether the blind position was genuinely blind is the whole
        # mechanism.
        sa.Column("ordering", _enum("deliberation_ordering"), nullable=False),
        sa.Column("user_response", sa.Text(), nullable=False),
        sa.Column("outcome", _enum("deliberation_outcome"), nullable=False),
        sa.Column("what_changed_her_mind", sa.Text(), nullable=True),
        # The seed of the prediction ledger.
        sa.Column("both_positions", sa.Text(), nullable=True),
        sa.Column("predictions", sa.Text(), nullable=True),
        sa.Column("classification", _enum("deliberation_classification"), nullable=False),
        sa.Column("classified_by", _enum("deliberation_classified_by"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_deliberations"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_deliberations_project_id",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_deliberations_conversation_id",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="fk_deliberations_message_id",
            ondelete="NO ACTION",
        ),
        sa.CheckConstraint(
            "outcome <> 'updated' OR what_changed_her_mind IS NOT NULL",
            name="updated_requires_what_changed_her_mind",
        ),
    )

    # --- §2.3 — no hard delete ----------------------------------------------

    op.execute(FORBID_HARD_DELETE_FUNCTION)
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_forbid_hard_delete "
            f"BEFORE DELETE OR TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION val_forbid_hard_delete()"
        )


def downgrade() -> None:
    """Remove the Layer 0 schema entirely, leaving an empty database."""
    for table in TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_forbid_hard_delete ON {table}")
    op.execute("DROP FUNCTION IF EXISTS val_forbid_hard_delete()")

    op.drop_table("deliberations")
    op.drop_table("execution_events")
    op.drop_table("model_calls")
    op.drop_index("uq_personas_single_active", table_name="personas")
    op.drop_table("personas")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("projects")

    for name in reversed(list(ENUM_TYPES)):
        op.execute(f"DROP TYPE {name}")

    op.execute("DROP EXTENSION IF EXISTS vector")
