"""The xAI adapter — preparation only, ruled 8 September 2026. Not registered.

xAI is **not admitted**. No registry entry names this adapter, `startup` does
not build it, and no Protected content may reach it until Lord Armand rules
xAI eligible and admitted. It exists so the one structural condition of that
ruling is already true when it comes: **the zero-data-retention guard**.

xAI documents (`docs.x.ai/developers/faq/security`, read 8 September 2026)
that under ZDR "API request inputs (i.e., your prompt) and outputs (i.e., the
tokens generated by the LLM) are never persisted to disk", that ZDR is applied
team-wide, and that "every API response includes an `x-zero-data-retention`
header set to `"true"` or `"false"`". This adapter reads that header on every
response and **fails closed**: a response without the header, or with any
value other than `true`, is refused as a data-policy failure and its text is
never handed onward — the call is still recorded and paid for, honestly,
because it happened.

The wire dialect is OpenAI-compatible Chat Completions on xAI's own domain
(`https://api.x.ai/v1`), which is xAI's API and not another provider's; the
OpenAI SDK is used as a client library only. Prompt caching on xAI is
automatic and its behaviour under ZDR is not established under the evidence
bar, so this adapter sends **no** cache key or conversation header — nothing
that would make a cache entry deliberately reusable — and reports no cache
figures; `cache_ttl` is accepted and ignored.
"""

from collections.abc import Mapping
from typing import Any

import openai

from val_domain.gateway import (
    CacheTtl,
    GatewayError,
    GatewayErrorKind,
    Message,
    ModelConfig,
    ReasoningEffort,
    TerminalState,
)
from val_providers.base import ProviderResult, normalize

#: The header xAI documents as the per-response ZDR confirmation.
ZDR_HEADER = "x-zero-data-retention"

XAI_BASE_URL = "https://api.x.ai/v1"

_EFFORT: dict[ReasoningEffort, str] = {
    ReasoningEffort.LOW: "low",
    ReasoningEffort.MEDIUM: "medium",
    ReasoningEffort.HIGH: "high",
}

_FINISH_REASONS: dict[str, TerminalState] = {
    "stop": TerminalState.COMPLETE,
    "length": TerminalState.TRUNCATED,
    "content_filter": TerminalState.FILTERED,
}


def zdr_confirmed(headers: Mapping[str, str]) -> bool:
    """Whether the response affirms zero data retention. Absent is not true."""
    value = headers.get(ZDR_HEADER)
    if value is None:
        # Header names are case-insensitive on the wire; a mapping that kept
        # the provider's casing is searched once more, deliberately.
        for name, candidate in headers.items():
            if name.lower() == ZDR_HEADER:
                value = candidate
                break
    return value is not None and value.strip().lower() == "true"


class XAIAdapter:
    """xAI, speaking the normalized contract, refusing without a ZDR affirmation."""

    name = "xai"

    def __init__(self, api_key: str) -> None:
        self._client = openai.OpenAI(api_key=api_key, base_url=XAI_BASE_URL)

    def complete(
        self,
        config: ModelConfig,
        messages: tuple[Message, ...],
        system: str | None,
        max_output_tokens: int,
        output_schema: Mapping[str, object] | None = None,
        cache_ttl: CacheTtl | None = None,
    ) -> ProviderResult:
        """Run one completion, or raise the normalized error.

        The response is read raw so its headers are visible; the ZDR guard
        runs before the body is looked at.
        """
        del cache_ttl  # accepted, never sent: see the module docstring
        turns: list[dict[str, str]] = []
        if system is not None:
            turns.append({"role": "system", "content": system})
        turns.extend(
            {"role": "user" if m.role == "user" else "assistant", "content": m.content}
            for m in messages
        )
        request: dict[str, Any] = {
            "model": config.model_identifier,
            "messages": turns,
            "max_completion_tokens": max_output_tokens,
        }
        if config.reasoning_effort is not ReasoningEffort.NOT_APPLICABLE:
            request["reasoning_effort"] = _EFFORT[config.reasoning_effort]
        if output_schema is not None:
            request["response_format"] = {
                "type": "json_schema",
                "json_schema": {
                    "name": "val_output",
                    "schema": dict(output_schema),
                    "strict": True,
                },
            }
        try:
            raw = self._client.chat.completions.with_raw_response.create(**request)
        except Exception as error:
            raise normalize(error, self.name) from error

        headers = getattr(raw, "headers", None) or {}
        if not zdr_confirmed(headers):
            observed = headers.get(ZDR_HEADER, "absent") if hasattr(headers, "get") else "absent"
            raise GatewayError(
                GatewayErrorKind.NOT_ELIGIBLE,
                f"{self.name}: the response did not affirm zero data retention "
                f"({ZDR_HEADER}: {observed}). The text is withheld and this route is "
                "unusable for Protected content until ZDR is affirmed on every response "
                "(ruling, 8 September 2026).",
            )

        response = raw.parse()
        choice = (getattr(response, "choices", None) or [None])[0]
        message = getattr(choice, "message", None)
        text = getattr(message, "content", None) or ""
        refusal = getattr(message, "refusal", None)
        finish = getattr(choice, "finish_reason", None) or ""
        terminal = (
            TerminalState.REFUSED if refusal else _FINISH_REASONS.get(finish, TerminalState.UNKNOWN)
        )
        usage = getattr(response, "usage", None)
        return ProviderResult(
            text=str(refusal) if refusal else text,
            terminal=terminal,
            tokens_in=getattr(usage, "prompt_tokens", None),
            tokens_out=getattr(usage, "completion_tokens", None),
            provider_request_id=getattr(response, "id", None),
            stop_reason=finish or None,
            stop_details="refusal item present" if refusal else None,
        )
